version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mtendere-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mtendere_edu
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: mtendere-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mtendere.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  pgdata:
