services:
  app:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports: 
    - "3000:80"
    
  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: mtendere-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - db
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mtendere.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  pgdata:
